spring:
    kafka:
        bootstrap-servers: kafka:9092
    cloud:
        stream:
            bindings:
                nounfunction-in-0:
                    destination: nounrequest
                nounfunction-out-0:
                    destination: nounresponse
